### ISSUE TITLE
Option to set "insert to current position" as default

### ISSUE THREAD

**Issue by BenRoe** [tgreen7/vscode_extension_node_require#10]
I use the command pallet to trigger the extension.  
It would be great to have an option, to change the default behavior to insert the `require` in the current position.
Or an additional shortcut `ctrl+shift+4` to insert a destructing import at the current position.

**Comment by tgreen7** [comment]
@BenRoe Sorry I am a little confused. Do you mean insert the reference at the current position or the whole import statement?

Also for the insert a destructuring import at current position how would that look. Lets say I am importing three items would I insert them all.

I can take a look at this once this is cleared up. 

Thanks!

**Comment by BenRoe** [comment]
Current behavior is:  
If i import a module via Command Pallet, it will be inserted at the *bottom of the import block*.  
  
I want:  
If i import a module via Command Pallet, it will be inserted at the *current cursor position*.

Or simply add an shortcut `ctrl+shift+4` to insert destructing import at the current position.   
This shortcut behaves similar to `ctrl+shift+3` but inserts the code at the current cursor position.  
That would be great.

**Comment by tgreen7** [comment]
@BenRoe I have added the setting "insertAtCursor" which make all requires insert at the cursor. However, this is a boolean option so it will completely disable inserting at the end of the import blocks.

**Comment by BenRoe** [comment]
@tgreen7 many thanks, that works great.
