### ISSUE TITLE
support importName starts with _

### ISSUE THREAD

**Issue by dolsup** [tgreen7/vscode_extension_node_require#11]
Hello!
Thank you for your awesome extension.

I usually use camelCase for `importName` and so the default settings couldn't be any problem, but recently I need to get importName which starts with `_` like `_ctx` for a special use case. (It's related to default eslint exception pattern)
when I import a dependency with name `_ctx.js`, I get:
```js
const _tx = require('../../query/_ctx');
```
It doesn't seem to make sense.
I hope you to consider this issue. Thank you

**Comment by dolsup** [comment]
P.S
The form that I want is `const _ctx = ...`

**Comment by tgreen7** [comment]
hey @dolsup. Yeah this does seem weird. Let me look into it

**Comment by tgreen7** [comment]
@dolsup Ok I have published a fix. Let me know if it works for you.

**Comment by dolsup** [comment]
Thanks! I'll check it

**Comment by dolsup** [comment]
It works! Thank you 🤣
