### ISSUE TITLE
Add support for import all

### ISSUE THREAD

**Issue by ejose19** [tgreen7/vscode_extension_node_require#13]
It's useful when coding typescript in the server, to import all instead of the current default import (which not all libreries have)

maybe ctrl + shift + 4 to do:

import * as request from "superagent";

in contrast to the current way of:

import request from "superagent"; 

(Which triggers "module superagent has no default export"

**Comment by tgreen7** [comment]
@ejose19 Yep this sounds like a great thing to add. Feel free to open a pr but I'll look into it when i get a chance.

**Comment by tgreen7** [comment]
@ejose19 I have added this option and will close this ticket. Please feel free to reopen if there is still an issue.

I did not register the keyboard shortcut but you can add 
```
{
    "key": "ctrl+shift+4",
    "command": "node_require.importAll"
  }
```
to your keybindings.json to add it.

**Comment by ejose19** [comment]
Working as expected. Thank you very much.
