### ISSUE TITLE
It doesn't work with multi-line require statements

### ISSUE THREAD

**Issue by yehtutlwin** [tgreen7/vscode_extension_node_require#17]
If I have the following require statement,
```
var debug = require("debug")(
  `${process.env.APP_NAME}:controllers/${path.basename(__filename)}`
);
```
Then a new require will be inserted just below the first line, so the end result becomes:
```
var debug = require("debug")(
const abc = require('abc');   // <----
  `${process.env.APP_NAME}:controllers/${path.basename(__filename)}`
);
```

**Comment by tgreen7** [comment]
@yehtutlwin Definitely a bug. 

This is a bit tricky because currently the code goes through each line in the file separately. This makes it difficult to handle multiline issues.

**Comment by tgreen7** [comment]
@yehtutlwin I am not thrilled with my fix (https://github.com/tgreen7/vscode_extension_node_require/commit/018beb0b47486ff994c88757259bb98e92cae2fd) but it seems to work.

Feel free to reopen if there are any issues.
