### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Zorono** [tgreen7/vscode_extension_node_require#18]
- Issue Type: `Performance`
- Extension Name: `vs-code-node-require`
- Extension Version: `1.4.7`
- OS Version: `Linux x64 5.8.0-33-generic`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/tgreen7.vs-code-node-require-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by tgreen7** [comment]
@Zorono Does this happen randomly or only while performing a require? The extension should only be active when using the require command.

**Comment by tgreen7** [comment]
Needs more info.
