### ISSUE TITLE
Support for npm workspaces

### ISSUE THREAD

**Issue by JosephClay** [tgreen7/vscode_extension_node_require#19]
Dependencies installed via an [npm workspaces](https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md) aren't available as a module

[Example repo to reproduce](https://github.com/JosephClay/node-require-npm-workspace-test)

**Comment by tgreen7** [comment]
I looked into this a little but got stuck. I am not sure the best way to get a list of workspace packages.
