### ISSUE TITLE
Allow extensions and index.js

### ISSUE THREAD

**Issue by jaguilar87** [tgreen7/vscode_extension_node_require#20]
File extensions [are mandatory on node 14+](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions), it would be great if we had a config option to stop hiding extensions (and also stop removing `/index.js`)

Moreover, it might be clever to add `.mjs` to the list of files supported

**Comment by tgreen7** [comment]
ok i added `keepFileExtension` option to settings.
I also added support for `.mjs`.

**Comment by tgreen7** [comment]
let me know if that works. feel free to reopen this issue if there are any problems.
