### ISSUE TITLE
Extension adds module name automatically

### ISSUE THREAD

**Issue by sushanyadav** [tgreen7/vscode_extension_node_require#22]
Every time I import something it adds a module name automatically and I've to remove it manually :(.

_at line 3_

![issue](https://user-images.githubusercontent.com/53527664/124597288-002d8f80-de83-11eb-9d9f-74c3fb380388.gif)

**Comment by tgreen7** [comment]
@sushanyadav which command are you using? It looks like you are using `node_require.requireAndInsert` (ctrl+shift+2) instead of `node_require.require` (ctrl+shift+1)

**Comment by sushanyadav** [comment]
> @sushanyadav which command are you using? It looks like you are using `node_require.requireAndInsert` (ctrl+shift+2) instead of `node_require.require` (ctrl+shift+1)

I didn't know there was a certain command for each.  😄 

Thank u.  ❤️ 
I am closing the issue.
