### ISSUE TITLE
Restrict import locations

### ISSUE THREAD

**Issue by RobertSandiford** [tgreen7/vscode_extension_node_require#23]
I have an issue using this plugin with typescript - the JS export files are given as options to import from, not just the TS source.

Is there a way to limit which folders or file extensions can be imported from?

Thanks!

**Comment by tgreen7** [comment]
@RobertSandiford 

You can use 

```json
"node_require.exclude": [
    "node_modules",
    "typings",
    "dist",
    "bin",
    "build",
    "tmp"
  ],
```

so that files will not be added to the require list. 

Does that solve your issue?

**Comment by RobertSandiford** [comment]
Yes, perfect!

Thanks for the help!
