### ISSUE TITLE
require get inserted before shebang

### ISSUE THREAD

**Issue by jfromaniello** [tgreen7/vscode_extension_node_require#6]
The `node_require.require` action inserts the require line before the shebang, eg:

```javascript
#!/usr/bin/env node

module.exports = function() {}
```

If you insert a require here it gets to the top.

**Comment by einarlove** [comment]
This pull request makes the case conversion on variable names retain the capitalisation of words.

**old**
import XmlImporter from './XMLImporter'
**new**
import XMLImporter from './XMLImporter'

**old**
```js
`import globalIdResolver from './globalIDResolver'`
**new**
```js
import globalIDResolver from './globalIDResolver'
```

**Comment by josh-renton** [comment]
It is the same for 'use-strict'. The require is inserted above the 'use-strict', not below it

**Comment by tgreen7** [comment]
@jfromaniello Sorry for the delay. I just pushed a fix for this. Let me know if that works!
